application: forza-quattro
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /forzaquattro\.(html|js)$
  static_files: forzaquattro.\1
  upload: forzaquattro\.(html|js)$

- url: /.*
  script: main.application

